server:
  ssl:
    enabled: true
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443
spring:
  jpa:
    properties:
      show_sql: true
      hibernate:
        format_sql: true
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace