spring:
  jpa:
    properties:
      show_sql: true
      hibernate:
        format_sql: true
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
server:
   port: 443
   ssl:
      key-store: keystore.p12
      keyStoreType: PKCS12
      keyAlias: tomcat